name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: Feature description
  - type: textarea
    attributes:
      label: Use case
